### PR TITLE
Copy post link

### PR DESCRIPTION
**Pull request by lucacorbucci**
Hi, I implemented a feature to copy the url of the reddit post from the main page of the app #14.
When I copy the url to the clipboard I show a simple Alert Dialog on the screen that is automatically dismissed after 1 second.

### CODE REVIEW

**Comment by mzegar** [comment]
Hey, merge conflicts will need to be solved, and I'll check it out.

**Comment by lucacorbucci** [comment]
> Hey, merge conflicts will need to be solved, and I'll check it out.

Hi, I guess I did some mistakes with git, if you prefer I can delete this PR and make another one without conflicts.

**Comment by mzegar** [comment]
https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git

I won't be able to merge it unless the conflicts are solved. 

You can either fix the merge conflicts and push it to this branch, or open a new branch.

**Comment by mzegar** [comment]
Closing due to https://github.com/mzegar/Retter/pull/25

**Pull request closed without merging**
