### PR TITLE
Screen Shots and Video Update

### PR DESCRIPTION
**Pull request by mayankparida**
I have updated the screenshots as well as the video onto the Readme file. Please do check and merge. Thank you.

### CODE REVIEW

**Comment by mzegar** [comment]
@mayankparida Do you mind moving the app icon to the screenshots folder? and restoring the original file in `assets/icon/Retter.png`? Then I'll be good to accept, thanks.

**Comment by mayankparida** [comment]
Yes Sure

**Comment by mayankparida** [comment]
Please do check now. I've made the required changes.

**Comment by mzegar** [comment]
Thanks for the work!

**Comment by mayankparida** [comment]
Thank you very very much!

**Pull request merged**
