### PR TITLE
implemented a better refresh post indicator

### PR DESCRIPTION
**Pull request by bigblackclock**

### CODE REVIEW

**Comment by mzegar** [comment]
Really good job done, this is exactly what I needed.

One change I would like (let me know if you need any help with this), is in regards to the "Loading posts...". Can we keep the `CircularProgressIndicator()` ONLY when you swap subreddits?

Ex.
You load into the app, you will see "Loading posts..." WITH the `CircularProgressIndicator()`
You swap subreddits from the side menu, you will see "Loading posts..." WITH the `CircularProgressIndicator()`
You pull down to refresh, you'll see what you currently have implemented, JUST "Loading posts..."

**Review by mzegar — CHANGES_REQUESTED** [review]
refer to my comment, good pr though

**Comment by bigblackclock** [comment]
will do it

**Comment by mzegar** [comment]
@bigblackclock Looks good, thanks for contributing, consider adding some more PR's in the future 👍

**Pull request merged**
