### PR TITLE
Copy post link

### PR DESCRIPTION
**Pull request by lucacorbucci**
Hi, I implemented a feature to copy the URL of the Reddit post from the main page of the app #14.
When I copy the URL to the clipboard I show a simple Alert Dialog on the screen that is automatically dismissed after 1 second.

I created a new PR, I hope I solved the problems of the previous one.

### CODE REVIEW

**Comment by mzegar** [comment]
Looks fine, conflicts need to be solved though.

**Comment by lucacorbucci** [comment]
Ok, I'm sorry but I don't know how to solve the conflicts.

**Comment by mzegar** [comment]
@lucacorbucci Hey, no worries, there is always a time to learn.

https://www.youtube.com/watch?v=XX-Kct0PfFc

Here is a good resource,  I suggest you check it out since merge conflicts will be something you'll need to deal with in the future.

Basically, what's happened, the files `lib/common/subredditPost.dart` & `lib/main.dart` have been changed on the master branch quite a lot (by me). Git is now unable to figure out where to place your changes for when they merge them in. Check out the video for a guide.

**Comment by lucacorbucci** [comment]
Hi, thank you for your patience and for the link. I think that I have managed to solve the conflict (and also to learn something new about Git).

P.S. Do you have a group or a Slack channel for this open source project?

**Comment by mzegar** [comment]
@lucacorbucci yup, seems like you resolved the merge conflicts property, good stuff.

Nope, I don't have a group or slack channel, I just don't think there would be that many people interested.

**Pull request merged**
